export default function getPaintings() {
    return [
        {
            key: "bird1",
            src: "/_photographs/bird1.jpg",
            imgWidth: 1213,
            imgHeight: 1536,
            title: "Bird1",
        },
        {
            key: "bird2",
            src: "/_photographs/bird2.jpg",
            imgWidth: 1213,
            imgHeight: 1536,
            title: "Bird2",
        },
        {
            key: "berry",
            src: "/_photographs/berry.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "black_cockatoo",
            src: "/_photographs/black_cockatoo.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "blue",
            src: "/_photographs/blue.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "burb",
            src: "/_photographs/burb.png",
            imgWidth: 1600,
            imgHeight: 1428,
            title: "Bird3",
        },
        {
            key: "berry",
            src: "/_photographs/berry.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "circle_duck",
            src: "/_photographs/circle_duck.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "cockatoo",
            src: "/_photographs/cockatoo.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "duck",
            src: "/_photographs/duck.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "fruit",
            src: "/_photographs/fruit.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "gold",
            src: "/_photographs/gold.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "happy",
            src: "/_photographs/happy.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Bird3",
        },
        {
            key: "head",
            src: "/_photographs/head.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "hello",
            src: "/_photographs/hello.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "kook",
            src: "/_photographs/kook.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Bird3",
        },
        {
            key: "leaf",
            src: "/_photographs/leaf.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "lyre",
            src: "/_photographs/lyre.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "nest",
            src: "/_photographs/nest.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "nestle",
            src: "/_photographs/nestle.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "nom",
            src: "/_photographs/nom.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "owl",
            src: "/_photographs/owl.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "parrot",
            src: "/_photographs/parrot.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Bird3",
        },
        {
            key: "perch",
            src: "/_photographs/perch.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "perch2",
            src: "/_photographs/perch2.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "plague_doctor",
            src: "/_photographs/plague_doctor.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "smol",
            src: "/_photographs/smol.png",
            imgWidth: 1600,
            imgHeight: 1148,
            title: "Bird3",
        },
        {
            key: "stick",
            src: "/_photographs/stick.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "wat",
            src: "/_photographs/wat.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "watchu_lookin_at",
            src: "/_photographs/watchu_looking_at.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "what",
            src: "/_photographs/what.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "what2",
            src: "/_photographs/what2.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
        {
            key: "zorro",
            src: "/_photographs/zorro.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bird3",
        },
    ];
}