

import blue_vase_of_flowers from "../../public/_paintings/blue_vase_of_flowers.jpg";
import blue_vase_with_fallen_camellias from "../../public/_paintings/blue_vase_with_fallen_camellias.jpg";
import camellias_in_glass_vase from "../../public/_paintings/camellias_in_glass_vase.jpg";
import comp_blue_vase_blue_table from "../../public/_paintings/comp_blue_vase_blue_table.jpg"
import comp_green_vase_camelias from "../../public/_paintings/comp_green_vase_camelias.jpg"
import comp_green_vase_camelias2 from "../../public/_paintings/comp_green_vase_camelias2.jpg"
import comp_lime_table from "../../public/_paintings/comp_lime_table.jpg"
import comp_white_vase from "../../public/_paintings/comp_white_vase.jpg"
import comp_yellow_vase from "../../public/_paintings/comp_yellow_vase.jpg"
import end_of_summer from "../../public/_paintings/end_of_summer.jpg"
import flowers_with_a_lemon from "../../public/_paintings/flowers_with_a_lemon.jpg"
import flowers_with_pomegranates from "../../public/_paintings/flowers_with_pomegranates.jpg"
import fowler_bottle from "../../public/_paintings/fowler_bottle.jpg"
import garden_posie from "../../public/_paintings/garden_posie.jpg"
import grandmas_vase from "../../public/_paintings/grandmas_vase.jpg"
import lemons_in_sicilian_bowl from "../../public/_paintings/lemons_in_sicilian_bowl.jpg"
import mandarins from "../../public/_paintings/mandarins.jpg"
import milk_bottle_vase from "../../public/_paintings/milk_bottle_vase.jpg"
import pink_and_yellow_stock from "../../public/_paintings/pink_and_yellow_stock.jpg"
import pinks_in_full_bloom from "../../public/_paintings/pinks_in_full_bloom.jpg"
import quinces from "../../public/_paintings/quinces.jpg"
import the_purple_vase from "../../public/_paintings/the_purple_vase.jpg"
import zinnias from "../../public/_paintings/zinnias.jpg"

export default function getPaintings() {
    return [
        {
            key: "blue_vase_of_flowers",
            src: "/_paintings/blue_vase_of_flowers.jpg",
            imgWidth: 1213,
            imgHeight: 1536,
            title: "Blue vase of flowers",
            date: "2015",
            forSale: false,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "blue_vase_with_fallen_camellias",
            src: "/_paintings/blue_vase_with_fallen_camellias.jpg",
            imgWidth: 1205,
            imgHeight: 1536,
            title: "Blue Vase with Fallen Camellias",
            date: "2020",
            forSale: false,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "camellias_in_glass_vase",
            src: "/_paintings/camellias_in_glass_vase.jpg",
            imgWidth: 1195,
            imgHeight: 1536,
            title: "Camellias in a glass vase",
            date: "2015",
            forSale: false,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_blue_vase_blue_table",
            src: "/_paintings/comp_blue_vase_blue_table.jpg",
            imgWidth: 1144,
            imgHeight: 1536,
            title: "Blue Vase Blue Table",
            date: "2020",
            forSale: true,
            sold: true,
            price: 350,
            height: 40,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_green_vase_camelias",
            src: "/_paintings/comp_green_vase_camelias.jpg",
            imgWidth: 1144,
            imgHeight: 1536,
            title: "Green Vase with Camellias",
            date: "2020",
            forSale: true,
            sold: false,
            price: 400,
            height: 40,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_green_vase_camelias2",
            src: "/_paintings/comp_green_vase_camelias2.jpg",
            imgWidth: 1232,
            imgHeight: 1536,
            title: "Green Vase with Camellias 2",
            date: "2020",
            forSale: true,
            sold: false,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_lime_table",
            src: "/_paintings/comp_lime_table.jpg",
            imgWidth: 1190,
            imgHeight: 1536,
            title: "Glass Jar on Lime Table",
            date: "2020",
            forSale: true,
            sold: true,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_white_vase",
            src: "/_paintings/comp_white_vase.jpg",
            imgWidth: 1196,
            imgHeight: 1536,
            title: "White Vase",
            date: "2020",
            forSale: true,
            sold: false,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "comp_yellow_vase",
            src: "/_paintings/comp_yellow_vase.jpg",
            imgWidth: 1206,
            imgHeight: 1536,
            title: "Yellow Vase",
            date: "2020",
            forSale: true,
            sold: false,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "end_of_summer",
            src: "/_paintings/end_of_summer.jpg",
            imgWidth: 1126,
            imgHeight: 1536,
            title: "End of Summer",
            date: "2021",
            forSale: false,
            sold: false,
            price: 350,
            height: 41,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "flowers_with_a_lemon",
            src: "/_paintings/flowers_with_a_lemon.jpg",
            imgWidth: 1215,
            imgHeight: 1536,
            title: "Flowers with a lemon",
            date: "2015",
            forSale: true,
            sold: false,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "flowers_with_pomegranates",
            src: "/_paintings/flowers_with_pomegranates.jpg",
            imgWidth: 1494,
            imgHeight: 1536,
            title: "Flowers with pomegranates",
            date: "2017",
            forSale: true,
            sold: false,
            price: 450,
            height: 61,
            width: 61,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "fowler_bottle",
            src: "/_paintings/fowler_bottle.jpg",
            imgWidth: 1075,
            imgHeight: 1379,
            title: "Fowler Jar",
            date: "2020",
            forSale: true,
            sold: true,
            price: 350,
            height: 35.5,
            width: 28,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "garden_posie",
            src: "/_paintings/garden_posie.jpg",
            imgWidth: 1219,
            imgHeight: 1536,
            title: "Garden Posie",
            date: "2021",
            forSale: true,
            sold: false,
            price: 400,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "grandmas_vase",
            src: "/_paintings/grandmas_vase.jpg",
            imgWidth: 1186,
            imgHeight: 1536,
            title: "Grandma's vase",
            date: "2020",
            forSale: true,
            sold: false,
            price: 450,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "lemons_in_sicilian_bowl",
            src: "/_paintings/lemons_in_sicilian_bowl.jpg",
            imgWidth: 1536,
            imgHeight: 1294,
            title: "Lemons in a Sicilian bowl",
            date: "2020",
            forSale: true,
            sold: true,
            price: 300,
            height: 25,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "mandarins",
            src: "/_paintings/mandarins.jpg",
            imgWidth: 1152,
            imgHeight: 1536,
            title: "Mandarins",
            date: "2020",
            forSale: false,
            height: 31,
            width: 25,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "mid_winter_blooms",
            src: "/_paintings/mid_winter_blooms.png",
            imgWidth: 1196,
            imgHeight: 1600,
            title: "Mid Winter Blooms",
            date: "2022",
            forSale: true,
            sold: false,
            price: 400,
            height: 40,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "milk_bottle_vase",
            src: "/_paintings/milk_bottle_vase.jpg",
            imgWidth: 1302,
            imgHeight: 1536,
            title: "Milk Bottle Vase",
            date: "2020",
            forSale: true,
            sold: true,
            price: 250,
            height: 31,
            width: 25,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "pink_and_yellow_stock",
            src: "/_paintings/pink_and_yellow_stock.jpg",
            imgWidth: 1183,
            imgHeight: 1536,
            title: "Pink and yellow stock",
            date: "2016",
            forSale: false,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "pinks_in_full_bloom",
            src: "/_paintings/pinks_in_full_bloom.jpg",
            imgWidth: 1149,
            imgHeight: 1536,
            title: "Pinks in Full Bloom",
            date: "2020",
            forSale: true,
            sold: true,
            price: 400,
            height: 40,
            width: 30,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "quinces",
            src: "/_paintings/quinces.jpg",
            imgWidth: 1524,
            imgHeight: 1536,
            title: "Four quinces",
            date: "2013",
            forSale: false,
            height: 61,
            width: 61,
            paint: "acrylic",
            material: "board",
        },
        {
            key: "the_purple_vase",
            src: "/_paintings/the_purple_vase.jpg",
            imgWidth: 1198,
            imgHeight: 1536,
            title: "The Purple Vase",
            date: "2020",
            forSale: false,
            height: 50,
            width: 40,
            paint: "acrylic",
            material: "canvas",
        },
        {
            key: "zinnias",
            src: "/_paintings/zinnias.jpg",
            imgWidth: 945,
            imgHeight: 1536,
            title: "Zinnias",
            date: "1986",
            forSale: false,
            height: 110,
            width: 70,
            paint: "acrylic",
            material: "canvas",
        },
    ];
}