export default function getPaintings() {
    return [
        {
            key: "bird1",
            src: "/_photographs/bird1.jpg",
            imgWidth: 1213,
            imgHeight: 1536,
            title: "Silver Eye",
        },
        {
            key: "bird2",
            src: "/_photographs/bird2.jpg",
            imgWidth: 1213,
            imgHeight: 1536,
            title: "Spotted Pardalote",
        },
        {
            key: "golden_whistler",
            src: "/_photographs/golden_whistler.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Golden Whistler",
        },
        {
            key: "berry",
            src: "/_photographs/berry.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Yellow-faced Honeyeater",
        },
        {
            key: "black_cockatoo",
            src: "/_photographs/black_cockatoo.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Black Cockatoo",
        },
        {
            key: "blue",
            src: "/_photographs/blue.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Kingfisher",
        },
        {
            key: "burb",
            src: "/_photographs/burb.png",
            imgWidth: 1600,
            imgHeight: 1428,
            title: "Scarlet Robin",
        },
        {
            key: "circle_duck",
            src: "/_photographs/circle_duck.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Duck",
        },
        {
            key: "cockatoo",
            src: "/_photographs/cockatoo.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "White Cockatoo",
        },
        {
            key: "duck",
            src: "/_photographs/duck.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Wood Ducks",
        },
        {
            key: "fruit",
            src: "/_photographs/fruit.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Lorikeet",
        },
        {
            key: "gold",
            src: "/_photographs/gold.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "White Eared Honeyeater",
        },
        {
            key: "happy",
            src: "/_photographs/happy.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Gang-gang",
        },
        {
            key: "head",
            src: "/_photographs/head.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Black Cockatoos",
        },
        {
            key: "hello",
            src: "/_photographs/hello.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "New Holland Honeyeater",
        },
        {
            key: "kook",
            src: "/_photographs/kook.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Kookaburra",
        },
        {
            key: "leaf",
            src: "/_photographs/leaf.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Grey Shrike-thrush",
        },
        {
            key: "lyre",
            src: "/_photographs/lyre.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Lyrebird",
        },
        {
            key: "nest",
            src: "/_photographs/nest.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Mudlark",
        },
        {
            key: "nestle",
            src: "/_photographs/nestle.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Silver Eyes",
        },
        {
            key: "nom",
            src: "/_photographs/nom.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Gang-gang",
        },
        {
            key: "owl",
            src: "/_photographs/owl.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Tawny Frogmouth with two young on nest",
        },
        {
            key: "parrot",
            src: "/_photographs/parrot.png",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Lorikeets",
        },
        {
            key: "perch",
            src: "/_photographs/perch.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Eastern Yellow Robin",
        },
        {
            key: "perch2",
            src: "/_photographs/perch2.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Fantail",
        },
        {
            key: "plague_doctor",
            src: "/_photographs/plague_doctor.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Eastern Spinebill",
        },
        {
            key: "smol",
            src: "/_photographs/smol.png",
            imgWidth: 1600,
            imgHeight: 1148,
            title: "Fantail",
        },
        {
            key: "stick",
            src: "/_photographs/stick.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Black-winged Stilts",
        },
        {
            key: "wat",
            src: "/_photographs/wat.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Tawny Frogmouth",
        },
        {
            key: "watchu_lookin_at",
            src: "/_photographs/watchu_looking_at.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Pacific Black Duck",
        },
        {
            key: "what",
            src: "/_photographs/what.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Striated Pardalotes",
        },
        {
            key: "what2",
            src: "/_photographs/what2.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Striated Pardalotes",
        },
        {
            key: "zorro",
            src: "/_photographs/zorro.png",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Red-browed Finch",
        },
        {
            key: "crested_pigeon",
            src: "/_photographs/crested_pigeon.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Crested Pigeon",
        },
        {
            key: "crimson_rosella",
            src: "/_photographs/crimson_rosella.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Crimson Rosella",
        },
        {
            key: "duck1",
            src: "/_photographs/duck1.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Wood Ducks 2",
        },
        {
            key: "duck2",
            src: "/_photographs/duck2.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Wood Ducks 3",
        },
        {
            key: "female_gang_gang",
            src: "/_photographs/female_gang_gang.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Female Gang-gang",
        },
        {
            key: "male_gang_gang",
            src: "/_photographs/male_gang_gang.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Male Gang-gang",
        },
        {
            key: "kangaroos",
            src: "/_photographs/kangaroos.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Kangaroos",
        },
        {
            key: "king_parrot1",
            src: "/_photographs/king_parrot1.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "King Parrot",
        },
        {
            key: "king_parrot2",
            src: "/_photographs/king_parrot2.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "King Parrot 1",
        },
        {
            key: "bronze_winged_pigeon1",
            src: "/_photographs/bronze_winged_pigeon1.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Bronze Winged Pigeon",
        },
        {
            key: "bronze_winged_pigeon2",
            src: "/_photographs/bronze_winged_pigeon2.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Bronze Winged Pigeon 1",
        },
        {
            key: "eastern_spinebill",
            src: "/_photographs/eastern_spinebill.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Eastern Spinebill",
        },
        {
            key: "eastern_spinebill2",
            src: "/_photographs/eastern_spinebill2.jpg",
            imgWidth: 1600,
            imgHeight: 1517,
            title: "Eastern Spinebill 1",
        },
        {
            key: "grey_fantail",
            src: "/_photographs/grey_fantail.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Grey Fantail",
        },
        {
            key: "rainbow_lorikeet",
            src: "/_photographs/rainbow_lorikeet.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Rainbow Lorikeet",
        },
        {
            key: "raven",
            src: "/_photographs/raven.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Raven",
        },
        {
            key: "trees_lake_burley",
            src: "/_photographs/trees_lake_burley.jpg",
            imgWidth: 1200,
            imgHeight: 1600,
            title: "Trees by Lake Burley Griffin",
        },
        {
            key: "wattle_bird",
            src: "/_photographs/wattle_bird.jpg",
            imgWidth: 1600,
            imgHeight: 1200,
            title: "Wattle Bird",
        }
    ];
}